import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { ArrowDown, ArrowUpRight, Check, Contact, GitFork, Mail, Menu, MoveUpRight, Send, X } from 'lucide-react';
import { fetchGithubProjects, mockProjects, Project, skills } from './data';
import './styles.css';

const Github = GitFork;
const Linkedin = Contact;

const fadeUp = { hidden: { opacity: 0, y: 18 }, visible: { opacity: 1, y: 0, transition: { duration: .55 } } };
const navItems = [['Work', 'work'], ['About', 'about'], ['Contact', 'contact']];

function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [projects, setProjects] = useState<Project[]>(mockProjects);
  const [usingGithub, setUsingGithub] = useState(false);
  const [sent, setSent] = useState(false);
  const username = import.meta.env.VITE_GITHUB_USERNAME as string | undefined;

  useEffect(() => { if (username) fetchGithubProjects(username).then((items) => { if (items.length) { setProjects(items); setUsingGithub(true); } }).catch(() => undefined); }, [username]);
  const scrollTo = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); setMenuOpen(false); };

  return <div className="site-shell">
    <header className="topbar"><a href="#top" className="brand" onClick={() => scrollTo('top')}><span className="brand-mark">A</span><span>Alex Morgan</span></a><nav className={menuOpen ? 'nav mobile-open' : 'nav'}>{navItems.map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => scrollTo(id)}>{label}</a>)}<a className="nav-resume" href="#contact" onClick={() => scrollTo('contact')}>Resume <ArrowUpRight size={14} /></a></nav><button className="menu-button" aria-label="Toggle menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></header>

    <main id="top">
      <section className="hero section-wrap"><div className="hero-copy"><motion.p className="eyebrow" initial="hidden" animate="visible" variants={fadeUp}><span className="status-dot" /> Available for select projects</motion.p><motion.h1 initial="hidden" animate="visible" variants={fadeUp} transition={{ delay: .08 }}>I make complex<br /><em>things feel simple.</em></motion.h1><motion.p className="hero-sub" initial="hidden" animate="visible" variants={fadeUp} transition={{ delay: .16 }}>Product-minded frontend engineer crafting thoughtful digital experiences for people and the teams who serve them.</motion.p><motion.div className="hero-actions" initial="hidden" animate="visible" variants={fadeUp} transition={{ delay: .24 }}><button className="button primary" onClick={() => scrollTo('work')}>See my work <ArrowDown size={16} /></button><a className="button ghost" href="mailto:hello@alexmorgan.dev">Let's talk <Mail size={16} /></a></motion.div></div><div className="hero-side"><div className="hero-orbit"><div className="orbit-ring ring-one" /><div className="orbit-ring ring-two" /><div className="orbit-core"><span>AM</span></div><span className="orbit-label label-one">React</span><span className="orbit-label label-two">Ideas →</span><span className="orbit-label label-three">Human-first</span></div></div><div className="hero-socials"><span>Find me elsewhere</span><a href="https://github.com" target="_blank" rel="noreferrer"><Github size={17} /> GitHub</a><a href="https://linkedin.com" target="_blank" rel="noreferrer"><Linkedin size={17} /> LinkedIn</a><a href="mailto:hello@alexmorgan.dev"><Mail size={17} /> Email</a></div></section>

      <section id="work" className="section-wrap work-section"><div className="section-heading"><div><p className="eyebrow">01 / Selected work</p><h2>A few things I've<br /><em>helped bring to life.</em></h2></div><p className="section-note">A small selection of product work, experiments,<br />and side projects I’m proud of.</p></div><div className="project-grid">{projects.map((project, index) => <motion.article className="project-card" key={project.title} initial="hidden" whileInView="visible" viewport={{ once: true, amount: .2 }} variants={fadeUp} transition={{ delay: index * .08 }}><a href={project.liveUrl} target={project.liveUrl === '#' ? undefined : '_blank'} rel="noreferrer" className={`project-art bg-gradient-to-br ${project.gradient}`}><div className="art-noise" /><div className="art-label">{project.type}</div><div className="art-title">{project.title}<MoveUpRight /></div></a><div className="project-info"><div><h3>{project.title}</h3><p>{project.description}</p></div><div className="project-links"><a href={project.liveUrl} target={project.liveUrl === '#' ? undefined : '_blank'} rel="noreferrer">Live demo <ArrowUpRight size={14} /></a><a href={project.repoUrl} target={project.repoUrl === '#' ? undefined : '_blank'} rel="noreferrer">GitHub <Github size={14} /></a></div><div className="tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div></div></motion.article>)}</div>{usingGithub ? <p className="github-note"><Check size={14} /> Pulled from @{username}'s public GitHub repositories</p> : <p className="github-note">Showing curated placeholders · add <code>VITE_GITHUB_USERNAME</code> to load your repositories</p>}</section>

      <section id="about" className="section-wrap about-section"><div className="section-heading"><div><p className="eyebrow">02 / A little about me</p><h2>The person behind<br /><em>the pixels.</em></h2></div></div><div className="about-grid"><div className="about-quote">“Good software is invisible. It just helps people do the thing they came to do.”<span>— a principle I try to keep close</span></div><div className="about-copy"><p>I'm Alex, a frontend engineer based in Brooklyn, NY. I like working at the intersection of product thinking, visual craft, and good old-fashioned engineering.</p><p>These days, I'm focused on building accessible, resilient interfaces for early-stage teams who care deeply about their users. When I’m not at my desk, you’ll find me wandering through bookstores or making an overcomplicated dinner.</p><a href="#contact" onClick={() => scrollTo('contact')} className="text-link">More about me <ArrowUpRight size={16} /></a></div></div></section>

      <section className="section-wrap skills-section"><div className="section-heading"><div><p className="eyebrow">03 / My toolkit</p><h2>Tools for turning<br /><em>ideas into reality.</em></h2></div><p className="section-note">The technologies I reach for most often,<br />plus a few things I’m exploring.</p></div><div className="skills-grid">{skills.map((group, index) => <motion.div className="skill-group" key={group.label} initial="hidden" whileInView="visible" viewport={{ once: true }} variants={fadeUp} transition={{ delay: index * .08 }}><div className="skill-number">0{index + 1}</div><h3>{group.label}</h3>{group.items.map(item => <span key={item}>{item}</span>)}</motion.div>)}</div></section>

      <section id="contact" className="section-wrap contact-section"><div className="contact-intro"><p className="eyebrow">04 / Say hello</p><h2>Have a good idea?<br /><em>Let's make it real.</em></h2><p>I'm always open to hearing about interesting projects, collaborations, or just saying hi.</p><div className="contact-links"><a href="mailto:hello@alexmorgan.dev"><Mail size={17} /> hello@alexmorgan.dev</a><a href="https://linkedin.com" target="_blank" rel="noreferrer"><Linkedin size={17} /> LinkedIn</a><a href="https://github.com" target="_blank" rel="noreferrer"><Github size={17} /> GitHub</a></div></div><form className="contact-form" onSubmit={(event) => { event.preventDefault(); setSent(true); }}><label>Your name<input required placeholder="Jane Smith" /></label><label>Email address<input required type="email" placeholder="jane@company.com" /></label><label>Tell me a little about it<textarea required rows={4} placeholder="What are you working on?" /></label><button className="button primary" type="submit">{sent ? <>Message sent <Check size={16} /></> : <>Send message <Send size={16} /></>}</button></form></section>
    </main><footer><span>© {new Date().getFullYear()} Alex Morgan</span><span>Designed & built with intention.</span><button onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}>Back to top <ArrowUpRight size={14} /></button></footer>
  </div>;
}
export default App;
